# Hello World 

Quick Python Tutorial and Tips

This notebook contains my notes from Udemy Course "Python for the Jupyter Notebook". I highly recommend it for beginers: https://www.udemy.com/course/python-for-the-jupyter-notebook/


## Shortcuts 

- H : Help, show all shortcuts

In Edit Mode
- Shift + Enter : Run the current cell, select below (creates a new cell below if does not exists)
- Ctrl + Enter : Run selected cells
- Alt + Enter : Run the current cell, insert a new cell below
- Ctrl + S : Save and checkpoint

In Command Mode
- Enter : Edit mode
- A insert cell above
- B insert cell below
- X cut selected cells
- C copy selected cells
- V paste cells below
- DD
- Shift + V paste cells above


## NOTE: 

### Mac vs Windows/Linux
- Ctrl: command key ⌘
- Shift: Shift ⇧
- Alt: option ⌥
 
## Table of Contents 

- [Variables](#Variables)
  - [Casting Variables](#Casting_Variables)
- [Working_With_Strings](#Working_With_Strings)
  - [Slice_Notation](#Slice_Notation)
  - [Other_String_Methods](#Other_String_Methods)
  - [Format_String](#Format_String)
- [User_Inputs](#User_Inputs)
- [Decision_Making](#Decision_Making)
- [Loops](#Loops)
- [Collections_Lists](#Collections_Lists)
- [Collections_Dictionaries](#Collections_Dictionaries)
- [Collections_Tuples](#Collections_Tuples)
- [Collections_Sets](#Collections_Sets)
- [List_Comprehensions](#List_Comprehensions)
- [Lambda_Functions](#Lambda_Functions)
- [Dates_Times](#Dates_Times)
- [Functions](#Functions)
- [Classes](#Classes)
- [Exception_Handling](#Exception_Handling)
  - [Assertions](#Assertions)
  - [Try_Except_Finally](#Try_Except_Finally)
- [Modules_Libraries](#Modules_Libraries)
  - [Installing_Packages](#Installing_Packages)
  - [NumPy_Arrays](#NumPy_Arrays)
- [Random_Generation](#Random_Generation)



In [ ]:
print("Hello World")

In [ ]:
'''
Get list of the reserved words
'''
help("keywords")

## Variables 

Python is dynamic typed language; a variable can start with integer, and later on can be a string.


In [ ]:
# INTEGER
x = 100
y = 1000000000000000000000000000000000000000 #limited with the memory
print(x+y)
type(x)

In [ ]:
# FlOAT
x = 10.34
y = 3.4e6
print(x)
print(y)
type(x)

In [ ]:
# BOOLEAN
x = False
print(x)
type(x)

In [ ]:
# STRINGS
x = "Hi there"
y = 'Hello there 2'
print(x + " - " + y)
type(x)

### Casting_Variables

In [ ]:
# string
x = "1.5"
print("String: " + str(x))

# string 
y = float(x)
print("Float: " + str(y))

# integer
z = int(y)
print("Integer:" + str(z))


## Working_With_Strings

In [ ]:
myString = "hello world"
print(myString[0])

# get the last character 
print(myString[10])
# OR
print(myString[-1])
# OR 
print(myString[len(myString)-1])



### Slice_Notation

In [ ]:
# get after n
myString[3:]

In [ ]:
# get before n
myString[:3]

In [ ]:
# get between n and m
myString[3:7]

### Other_String_Methods

In [ ]:
# Find string in string
"Hello" in myString

In [ ]:
# To uppper
myString.upper()

In [ ]:
# To lower
myString.lower()

In [ ]:
# Capitalize
myString.capitalize()

In [ ]:
# Title
myString.title()

In [ ]:
# Check if string is a number
myString.isnumeric()


In [ ]:
# Pad 
myString.zfill(15)

### Format_String

In [ ]:
import sys
from datetime import date

name = "Omer"
language = "Python"
version = sys.version
today = date.today()

formattedStr = "Hello {}. You are using {} version {}. Today is {}".format(name, language,version, today)

print(formattedStr)


## User_Inputs

In [ ]:
name = input("Enter your name: ")

## Decision_Making

In [ ]:
yesno = input("Are you sure you want to continue [yes/no]?")
if yesno.lower()=="yes":
    print("Will continue")
elif yesno.lower()=="no":
    print("Will not continue")
else:
    print("Wrong entry")    
  


In [3]:
# not condition
val = input ("Enter a number less than 10: ")
if not int(val) < 10:
    print("{} is not less than 10".format(val))
else :
    print("Thank you")

Enter a number less than 10: 10
10 is not less than 10


## Loops


In [ ]:
# For loop
for x in range(4):
    print("hello")   # 4 spaces before print..

In [ ]:
myStr = "ABCDEFG"
for c in myStr:
    print(c)

In [ ]:
# while loop
x = 0 

while x <= 10:
    print(str(x))
    x = x +1 
    

In [ ]:
while True: 
    entry=input("Enter x to exit.")
    if entry.lower()=="x":
        break
    

## Collections_Lists

- Can contain different types

In [ ]:
shoppingList = ["Tesla Model S","yoghurt", "egg", "margarine", "tomato", "stinky socks", "OLED Tv", ]

print("Number of items to buy is " + str(len(shoppingList)))
      
print("option 1 ---------")    
for item in shoppingList:
    if item.lower() == "stinky socks":
        continue
    print(item)
    
print("\noption 2 ---------")    
for i, item in enumerate(shoppingList):
    if item.lower() == "stinky socks":
        continue
    print("{}. item: {}".format(i+1,item))
    
print("\nRemove items") 
shoppingList.remove("stinky socks")    # remove  
shoppingList.pop(0)                    # remove by using pop 
del shoppingList[len(shoppingList)-1]  # remove by using del

print("\nAdd new items") 
shoppingList.append("milk")      # add to the end
shoppingList.insert(0, "bread")  # insert to index 0

print("\nAdd another list") 
secondList = ["rice", "sugar", "baking soda"]
shoppingList.extend(secondList)
    
print("\nDid we forget the egg? ")    
if "egg" in shoppingList: 
    print("egg is in the list")
    
print("\nSort ---------")  
shoppingList.sort()
print(shoppingList)

print("\nReversed ---------")  
shoppingList.reverse()
print(shoppingList)

print("\nClear the list")
shoppinhList.clear()
print(len(shoppinhList)



## Collections_Dictionaries

- Collection of objects
- It is unordered
- It is changable
- It is indexed using key and value pairs

Syntax:
```python
variable = {"Key":"Value", "Key": "Value"}
```

In [ ]:
# Creating a dictionary
car = { "Make": "Nissan", "Model": "Altima", "Year": "2019" }
print(car)

print("\nAccessing to dictionary value ---------") 
print(car["Make"])
print(car.get("Make"))

print("\nGet the size ---------") 
len(car)

print("\nChange the value ---------") 
car["Model"] = "Maxima"
print(car["Model"])


print("\nLoop through keys and values --------- 1")  
for prop in car:
    print("{} : {}".format(prop, car[prop]))

print("\nLoop through keys and values --------- 2")  
for key, value in car.items():
    print("{} : {}".format(key, value))

print("\nCheck if value exists --------- ")
print("Make" in car)  # Returns True
print("Color" in car) # Returns False

print("\nRemove kv --------- ")
print("Year" in car) # Returns True
car.pop("Year")
print("Year" in car) # Returns False

print("\nClear Dictionary --------- ")
car.clear()
len(car)
   

## Collections_Tuples

- It is ordered
- It is indexed
- Allow Duplicates
- It is immutable, not changable. You need to crate a new tuple to change
- Smaller and Faster than a List

In [ ]:
print("\n Create a Tuple --------- ")
weekdays = ("Mon", "Tue", "Wed", "Thu", "Fri" ) # didn't add Sat and Sun to show changing
print(weekdays)

print("\n Access items by index --------- ")
print(weekdays[0]) # first
print(weekdays[-1]) # last 
print(weekdays[len(weekdays)-1]) # Use len to ge the latest
print(weekdays[3:]) # Print after the 3rd
print(weekdays[:3]) # Print until 3

print("\n Check if item exists --------- ")
print("Tue" in weekdays)

print("\n Look through items --------- ")
for day in weekdays:
    print(day)

print("\n Sort items --------- ")
sortedWeekdays = sorted(weekdays)
print(sortedWeekdays)

print("\n Changing tuple --------- ")
# we need to create a new tuple
missingDays = ("Sat", "Sun")
weekdays = weekdays + missingDays
print(weekdays)

print("\n Removing item from tuple --------- ")
# convert it to a list
tmp_weekdays = list(weekdays)
tmp_weekdays.remove("Sun")
tmp_weekdays.remove("Sat")
# convert back to tuple
weekdays = tuple(tmp_weekdays)
print(weekdays)


## Collections_Sets

- Not ordered
- Not indexed
- Items in the sets not changeable, but the set can be changed (add/remove items)
- items are unique
- High performance

In [ ]:
print("Create a set ----------")
workdays = { "Mon", "Tue", "Wed", "Thu" }
print(workdays)
print(len(workdays))

print("\n Check value ----------")
if "Tue" in workdays:
    print("Tue found")
else:
    print("Not found")

print("\n Looping through --------")
for d in workdays:
    print("Day : " + d)
    
print("\n Adding item --------")
workdays.add("Fri")
print(workdays)

print("\n Removing item --------")
workdays.remove("Fri")
print(workdays)
# or
workdays.discard("Thu")
print(workdays)


print("\n Operations - Union '|' (groups values, so, unique) --------")
workdays.add("Tue")
workdays.add("Fri")

weekends = { "Fri", "Sat", "Sun"}
weekdays = workdays | weekends
print(weekdays)


print("\n Operations - Intersect '&' (only the same values are kept) --------")
workdays2 = {"Mon"}
common = workdays & workdays2 
print (common)
# OR 
workdays2 = {"Mon", "Tue"}
common = workdays.intersection(workdays2)
print(common)


print("\n Operations - Difference '-' --------")
workdays2 = weekdays - weekends
print(workdays2)
# OR 
workdays2 = weekdays.difference(weekends)
print(workdays2)


print("\n Clear --------")
workdays.clear()
print(workdays)


    

## List_Comprehensions

- Used to create new lists from other iterables
- Alternative way to loops to create lists
- Usage
  ```python
  newList = [ output_expression() for(set of values to iterate) if(conditional filtering)]

  ```

In [ ]:
print(" Using a loop --------")
newnums = []
nums = [1,2,3,4,5,6,7,8,9,10]
for x in nums:
    newnums.append(x+10)
print(newnums)

print("\n Using a List Comprehension ------")
newnums = [ x+100 for x in nums ]
print(newnums)


print("\n Using a List Comprehension with condition ------")
newnums = [ x+1000 for x in nums if x<=5]
print(newnums)




## Lambda_Functions 

- Typically used with map() and filter() functions
  - map() function can be used to apply the lambda function to every item on an iterable (list, tuple, etc..)
- Heavily used in Pandas.
- Usage
  ```python
  variable = lambda x:y  #x is the function argument, y is the function body

  ```


In [ ]:
print("\n Basic usage  ------")
addFive = lambda x:x+5  # x is the argument, x+5 is the expression
print(addFive(10))

print("\n Somehow more advanced then the first  ------")
# create a new list by adding 5 to all items
myvalues = [1,2,3]
print(myvalues)
newvalues = list(map(lambda x:x+10, myvalues))
print(newvalues)



## Dates_Times

- Libs
  - datetime
  - date
  - timedelta
  - pytz  


In [ ]:
from datetime import date
from datetime import datetime

print("\n Get current date ------")
today = date.today()
print(today)


print("\n Get current date + time ------")
dt = datetime.now()
print(dt)

print("\n New date ------")
newdate = date(2010,1,1)
print(newdate)

print("\n New datetime ------")
newdt = datetime(2010,1,1, 3,45,0)
print(newdt)

print("\n Formatting datetime ------")
dt = datetime.now()
print(dt.strftime("%m-%d-%Y"))

print("\n Convert str to date ------")
strdate = "02/01/2010 05:00"
mydt = datetime.strptime(strdate, "%m/%d/%Y %I:%M")
print(type(mydt))
print(mydt)

print("\n Get date difference ------")
begindate = date(2010,1,1)
now = date.today()
difference = now-begindate  # returns datetime.timedelta)
print(type(difference))
print(difference)

print("\n Add date ------")
from datetime import timedelta
td = timedelta(days=365)
futuredate = date.today() + td
print(futuredate)


print("\n Time zones ------")
import pytz

local_dt = datetime.now()

london_tz = pytz.timezone("Europe/London")
london_dt = datetime.now(london_tz)

print("Local time : " + str(local_dt))
print("London time : " + str(london_dt))


## Functions

In [ ]:
# function with parameter (also set default param)
def Greetings(name="Omer"):
    print("Greetings " + name.upper())
Greetings()
Greetings("Melissa")


# Return  with default parameter
def Sum(value1, value2):
    return value1 + value2

print(Sum(10,4))


## Classes

In [ ]:
class ToDoList():
    __items = []
    
    # constructor
    def __init__(self,name):
        # public variable
        self.name = name
        
        # private variable
        self.__items = []
        
    def addItem(self, itemName):
        self.__items.append(itemName)        

    def remove(self, itemName):
        self.__items.remove(itemName)        

    def clearList(self):
        self.__items.clear()

    def getItems(self):
        return self.__items

    def printItems(self): # of course not a good idea to print here..
        print(self.__items)

        
myList = ToDoList(name="Shopping list")
myList.addItem("Egg")
myList.addItem("Bread")
myList.addItem("Milk")
myList.printItems()

myList.clearList()
myList.printItems()

    

## Exception_Handling

- Some of the built in exceptions
  1. SyntaxError
  2. TypeError
  3. ZeroDivisonError
  
  
- More : https://docs.python.org/3/library/exceptions.html



In [ ]:
# Raising an exception

value = input("Enter Y")
if not value == "Y":
    raise Exception("You didn't enter Y")


## Assertions

- Are used for debugging and testing

In [1]:
val = input("Enter a value greter than 20")
assert (int(val) > 20),"Value is not greater than 20"

Enter a value greter than 2025


## Try_Except_Finally

In [6]:
val = int(input("Enter a value greter than 20"))

try :
    if val > 20:
        print("Right value")
    else:
        raise Exception("Wrong value")   
except:
    print("And error has occured")
finally:
    print("Completed")

Enter a value greter than 204
And error has occured
Completed


## Modules_Libraries

```python
import math
from math import sqrt
from math import sqrt as s
from math import # absoulutely not recommended approach
```

- Scipy libraries: numpy, pandas, mathplot, ...
  - Scipy contains a lot of libraries for scientific implementations
  - Suitable for: mathematics, machine learning, artifical intelligicence, engineering,,
  
  

In [2]:
# USEFUL MODULES and LIBRARIES -------------------------
# All these libraries are included in Anaconda package

# MODULES -------------------
# numpy : Allows to work with multi-dimensional arrays
import numpy 

# pandas : Open source library, provides ready to use high-performance data structures
#          and data analysis tools, organize data in a tabular form and attach descritive labels to the rows
#          and columns of the table
#          Provides tools to work with timeseries and big data.. 
import pandas

# matplotlib : Comprehensive library for creating static, animated, and iteractive visualizations in Python
#              2d plotting library specially designed for visualization of NumPy computations
import matplotlib


# LIBRARIES ---------------------------
# random : Random number generator
import random

# statsmodels : Descriptive statistics, plotting functions, regressions
import statsmodels




### Installing_Packages

```shell
pip install <package_name>
```

```shell
pip install pandas-datareader

## NumPy_Arrays

- Similar to Lists
- numpy.array(list1, list2, list3,...)
-   the size of the lists should be the same
-   types o the list should be the same

array(...)

    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    


In [23]:
import numpy as np

a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11]]) # adding 2 lists to array
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
# get the shape of the array (like x,y)
a.shape

(3, 4)

In [22]:
# accessing to an item
a[1,2]

6

In [25]:
# getting the first list
a[0]

array([0, 1, 2, 3])

In [27]:
# setting a value
a[2,3]=15
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 15]])

## Random_Generation

- generates a random float in the range [0;1)

In [35]:
import random

# Random float between 0 and 1
prob = random.random()
print("random.random() : " + str(prob))

# Random integer number
num = random.randint(1,10)
print("random.randint(1,10) : " + str(num))



random.random() : 0.7124768780952047
random.randint(1,10) : 7


In [39]:
# Generating randomly generated matrix

import numpy

matrix = np.random.randint(1,10,(4,6)) # random numbers between 1 and 10,, matrix 4 by 6
matrix


array([[4, 7, 5, 1, 1, 9],
       [1, 4, 8, 6, 5, 5],
       [3, 3, 7, 1, 7, 3],
       [7, 5, 6, 6, 9, 9]])